/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.util.concurrent.Semaphore;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import proyecto2so.AI;
import proyecto2so.Company;
import proyecto2so.SO;
import proyecto2so.Simulacion;

/**
 *
 * @author Daniel Morillo
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    

    Semaphore mutex = new Semaphore(1);
    String RSNames[] = {"Mordecai", "Rigby", "Skips", "Musculoso", "Fantasmin", "Benson", "Thomas", "Papaleta", "Muerte", "AntiPapaleta", "Margarita", "CJ", "Aylin"};

    String RSPhotos[] = {"src/resources/mordecai.png", "src/resources/rigby.png", "src/resources/skips.png", "src/resources/musculoso.png", "src/resources/fantasmin.png", "src/resources/benson.png", "src/resources/thomas.png", "src/resources/papaleta.png", "src/resources/death.png", "src/resources/antipops.png", "src/resources/margarita.png", "src/resources/cj.png", "src/resources/aylin.png"};

    String AVNames[] = {"Aang", "Katara", "Sokka", "Toph", "Zuko", "Iroh", "Appa", "Momo", "Suki", "Azula", "Ozai", "Ty Lee", "Bumi"};

    String AVPhotos[] = {"src/resources/Aang.PNG", "src/resources/Katara.png", "src/resources/Sokka.PNG", "src/resources/Toph.PNG", "src/resources/Zuko.PNG", "src/resources/Iroh.png", "src/resources/Appa.PNG", "src/resources/Momo.PNG", "src/resources/Suki.PNG", "src/resources/Azula.PNG", "src/resources/Ozai.PNG", "src/resources/Ty-Lee.PNG", "src/resources/Bumi.PNG"};
    
    

    Company RSCompany = new Company('R', RSNames, RSPhotos);
    Company AVCompany = new Company('A', AVNames, AVPhotos);

    AI ai = new AI(5000, RSCompany, AVCompany, mutex );
    SO so = new SO(RSCompany, AVCompany, mutex);
    

    Simulacion simulacion = new Simulacion(RSCompany, AVCompany, so, ai);


    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        TimeField.setText(String.valueOf(ai.getBattleDuration()/1000));
        JLabel[] AIRSLabels = {RSIDLabel, RSFighterLabel, RSHPLabel, RSHabilityLabel, RSAtkLabel, RSAgilitylabel};
        JLabel[] AIAVLabels = {AVIDLabel, AVFighterLabel, AVHPLabel, AVHabilityLabel, AVATKLabel, AVAgilityLabel};
        
        JLabel[] RSPriority1Labels = {RSpr1_1image, RSpr1_1ID,RSpr1_2image, RSpr1_2ID,RSpr1_3image, RSpr1_3ID,RSpr1_4image, RSpr1_4ID };
        JLabel[] RSPriority2Labels = {RSpr2_1image, RSpr2_1ID,RSpr2_2image, RSpr2_2ID,RSpr2_3image, RSpr2_3ID,RSpr2_4image, RSpr2_4ID };
        JLabel[] RSPriority3Labels = {RSpr3_1image, RSpr3_1ID,RSpr3_2image, RSpr3_2ID,RSpr3_3image, RSpr3_3ID,RSpr3_4image, RSpr3_4ID };
        
        JLabel[] AVPriority1Labels = {AVpr1_1image, AVpr1_1ID,AVpr1_2image, AVpr1_2ID,AVpr1_3image, AVpr1_3ID,AVpr1_4image, AVpr1_4ID };
        JLabel[] AVPriority2Labels = {AVpr2_1image, AVpr2_1ID,AVpr2_2image, AVpr2_2ID,AVpr2_3image, AVpr2_3ID,AVpr2_4image, AVpr2_4ID };
        JLabel[] AVPriority3Labels = {AVpr3_1image, AVpr3_1ID,AVpr3_2image, AVpr3_2ID,AVpr3_3image, AVpr3_3ID,AVpr3_4image, AVpr3_4ID };
        
        JTextArea[] ReinforcementsLabels = {RSReinArea,AVReinArea};
        
        
        so.setRSPriority1Labels(RSPriority1Labels);
        so.setRSPriority2Labels(RSPriority2Labels);
        so.setRSPriority3Labels(RSPriority3Labels);
        
        so.setAVPriority1Labels(AVPriority1Labels);
        so.setAVPriority2Labels(AVPriority2Labels);
        so.setAVPriority3Labels(AVPriority3Labels);
        
        so.setReinforcementLabels(ReinforcementsLabels);
        
        ai.setRSLabels(AIRSLabels);
        ai.setAVLabels(AIAVLabels);
        ai.setStatus(statusIA);
        ai.getStatus().setText("Iniciando");
        
        simulacion.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RSFighterLabel = new javax.swing.JLabel();
        AVFighterLabel = new javax.swing.JLabel();
        RSHPLabel = new javax.swing.JLabel();
        RSHabilityLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RSAtkLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RSAgilitylabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AVHPLabel = new javax.swing.JLabel();
        AVHabilityLabel = new javax.swing.JLabel();
        AVATKLabel = new javax.swing.JLabel();
        AVAgilityLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RSIDLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AVIDLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RSpr1_4ID = new javax.swing.JLabel();
        RSpr1_4image = new javax.swing.JLabel();
        RSpr1_3ID = new javax.swing.JLabel();
        RSpr1_3image = new javax.swing.JLabel();
        RSpr1_2ID = new javax.swing.JLabel();
        RSpr1_2image = new javax.swing.JLabel();
        RSpr1_1ID = new javax.swing.JLabel();
        RSpr1_1image = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AVpr1_4ID = new javax.swing.JLabel();
        AVpr1_4image = new javax.swing.JLabel();
        AVpr1_3ID = new javax.swing.JLabel();
        AVpr1_3image = new javax.swing.JLabel();
        AVpr1_2ID = new javax.swing.JLabel();
        AVpr1_2image = new javax.swing.JLabel();
        AVpr1_1ID = new javax.swing.JLabel();
        AVpr1_1image = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        AVpr2_4ID = new javax.swing.JLabel();
        AVpr2_4image = new javax.swing.JLabel();
        AVpr2_3ID = new javax.swing.JLabel();
        AVpr2_3image = new javax.swing.JLabel();
        AVpr2_2ID = new javax.swing.JLabel();
        AVpr2_2image = new javax.swing.JLabel();
        AVpr2_1ID = new javax.swing.JLabel();
        AVpr2_1image = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        AVpr3_4ID = new javax.swing.JLabel();
        AVpr3_4image = new javax.swing.JLabel();
        AVpr3_3ID = new javax.swing.JLabel();
        AVpr3_3image = new javax.swing.JLabel();
        AVpr3_2ID = new javax.swing.JLabel();
        AVpr3_2image = new javax.swing.JLabel();
        AVpr3_1ID = new javax.swing.JLabel();
        AVpr3_1image = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        RSpr2_4ID = new javax.swing.JLabel();
        RSpr2_4image = new javax.swing.JLabel();
        RSpr2_3ID = new javax.swing.JLabel();
        RSpr2_3image = new javax.swing.JLabel();
        RSpr2_2ID = new javax.swing.JLabel();
        RSpr2_2image = new javax.swing.JLabel();
        RSpr2_1ID = new javax.swing.JLabel();
        RSpr2_1image = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        RSpr3_4ID = new javax.swing.JLabel();
        RSpr3_4image = new javax.swing.JLabel();
        RSpr3_3ID = new javax.swing.JLabel();
        RSpr3_3image = new javax.swing.JLabel();
        RSpr3_2ID = new javax.swing.JLabel();
        RSpr3_2image = new javax.swing.JLabel();
        RSpr3_1ID = new javax.swing.JLabel();
        RSpr3_1image = new javax.swing.JLabel();
        AVReinforcements = new javax.swing.JLabel();
        RSReinforcements = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RSReinArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        AVReinArea = new javax.swing.JTextArea();
        TimeField = new javax.swing.JTextField();
        TimeButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        statusIA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(RSFighterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, 150));
        getContentPane().add(AVFighterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 150, 150));
        getContentPane().add(RSHPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 68, 35));
        getContentPane().add(RSHabilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 68, 35));

        jLabel3.setText("HP: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 35));

        jLabel4.setText("Habilidad: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));
        getContentPane().add(RSAtkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 68, 35));

        jLabel6.setText("Ataque:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));
        getContentPane().add(RSAgilitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 68, 35));

        jLabel8.setText("Agilidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel1.setText("HP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        jLabel2.setText("Habilidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        jLabel5.setText("Ataque:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        jLabel7.setText("Agilidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));
        getContentPane().add(AVHPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 68, 35));
        getContentPane().add(AVHabilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 65, 34));
        getContentPane().add(AVATKLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 65, 36));
        getContentPane().add(AVAgilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 71, 35));

        jLabel9.setText("ID : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        RSIDLabel.setText(" ");
        getContentPane().add(RSIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 117, -1));

        jLabel10.setText("ID : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        AVIDLabel.setText(" ");
        getContentPane().add(AVIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 101, -1));

        jLabel11.setText("PRIORIDAD 1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 173, -1));

        RSpr1_4ID.setText("ID: ");
        getContentPane().add(RSpr1_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 56, -1));
        getContentPane().add(RSpr1_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 59, 67));

        RSpr1_3ID.setText("ID: ");
        getContentPane().add(RSpr1_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 56, -1));
        getContentPane().add(RSpr1_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 59, 67));

        RSpr1_2ID.setText("ID: ");
        getContentPane().add(RSpr1_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 56, -1));
        getContentPane().add(RSpr1_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 59, 67));

        RSpr1_1ID.setText("ID: ");
        getContentPane().add(RSpr1_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 56, -1));
        getContentPane().add(RSpr1_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 59, 67));

        jLabel20.setText("PRIORIDAD 1");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 6, 173, -1));

        AVpr1_4ID.setText("ID: ");
        getContentPane().add(AVpr1_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 104, 56, -1));
        getContentPane().add(AVpr1_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 30, 59, 67));

        AVpr1_3ID.setText("ID: ");
        getContentPane().add(AVpr1_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 104, 56, -1));
        getContentPane().add(AVpr1_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 30, 59, 67));

        AVpr1_2ID.setText("ID: ");
        getContentPane().add(AVpr1_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 102, 56, -1));
        getContentPane().add(AVpr1_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 28, 59, 67));

        AVpr1_1ID.setText("ID: ");
        getContentPane().add(AVpr1_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 102, 56, -1));
        getContentPane().add(AVpr1_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 28, 59, 67));

        jLabel29.setText("PRIORIDAD 2");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 154, 173, -1));

        AVpr2_4ID.setText("ID: ");
        getContentPane().add(AVpr2_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 252, 56, -1));
        getContentPane().add(AVpr2_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 178, 59, 67));

        AVpr2_3ID.setText("ID: ");
        getContentPane().add(AVpr2_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 252, 56, -1));
        getContentPane().add(AVpr2_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 178, 59, 67));

        AVpr2_2ID.setText("ID: ");
        getContentPane().add(AVpr2_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 250, 56, -1));
        getContentPane().add(AVpr2_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 176, 59, 67));

        AVpr2_1ID.setText("ID: ");
        getContentPane().add(AVpr2_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 250, 56, -1));
        getContentPane().add(AVpr2_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 176, 59, 67));

        jLabel38.setText("PRIORIDAD 3");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 286, 173, -1));

        AVpr3_4ID.setText("ID: ");
        getContentPane().add(AVpr3_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 384, 56, -1));
        getContentPane().add(AVpr3_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 310, 59, 67));

        AVpr3_3ID.setText("ID: ");
        getContentPane().add(AVpr3_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 384, 56, -1));
        getContentPane().add(AVpr3_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 310, 59, 67));

        AVpr3_2ID.setText("ID: ");
        getContentPane().add(AVpr3_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 382, 56, -1));
        getContentPane().add(AVpr3_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 308, 59, 67));

        AVpr3_1ID.setText("ID: ");
        getContentPane().add(AVpr3_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 382, 56, -1));
        getContentPane().add(AVpr3_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 308, 59, 67));

        jLabel47.setText("PRIORIDAD 2");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 173, -1));

        RSpr2_4ID.setText("ID: ");
        getContentPane().add(RSpr2_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 56, -1));
        getContentPane().add(RSpr2_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 59, 67));

        RSpr2_3ID.setText("ID: ");
        getContentPane().add(RSpr2_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 56, -1));
        getContentPane().add(RSpr2_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 59, 67));

        RSpr2_2ID.setText("ID: ");
        getContentPane().add(RSpr2_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 56, -1));
        getContentPane().add(RSpr2_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 59, 67));

        RSpr2_1ID.setText("ID: ");
        getContentPane().add(RSpr2_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 56, -1));
        getContentPane().add(RSpr2_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 59, 67));

        jLabel56.setText("PRIORIDAD 3");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 173, -1));

        RSpr3_4ID.setText("ID: ");
        getContentPane().add(RSpr3_4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 56, -1));
        getContentPane().add(RSpr3_4image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 59, 67));

        RSpr3_3ID.setText("ID: ");
        getContentPane().add(RSpr3_3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 56, -1));
        getContentPane().add(RSpr3_3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 59, 67));

        RSpr3_2ID.setText("ID: ");
        getContentPane().add(RSpr3_2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 56, -1));
        getContentPane().add(RSpr3_2image, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 59, 67));

        RSpr3_1ID.setText("ID: ");
        getContentPane().add(RSpr3_1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 56, -1));
        getContentPane().add(RSpr3_1image, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 59, 67));

        AVReinforcements.setText("REFUERZOS:");
        getContentPane().add(AVReinforcements, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 90, 69));

        RSReinforcements.setText("REFUERZOS:");
        getContentPane().add(RSReinforcements, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 110, 69));

        RSReinArea.setColumns(20);
        RSReinArea.setRows(5);
        jScrollPane1.setViewportView(RSReinArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 330, -1));

        AVReinArea.setColumns(20);
        AVReinArea.setRows(5);
        jScrollPane2.setViewportView(AVReinArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 340, -1));

        TimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 80, -1));

        TimeButton.setText("jButton1");
        TimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        jLabel12.setText("Estado de la IA:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));
        getContentPane().add(statusIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeFieldActionPerformed

    private void TimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeButtonActionPerformed
        // TODO add your handling code here:
        ai.setBattleDuration(Integer.parseInt(TimeField.getText())*1000);
        JOptionPane.showMessageDialog(this, "Duracion de Batalla Cambiada con Exito");
    }//GEN-LAST:event_TimeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVATKLabel;
    private javax.swing.JLabel AVAgilityLabel;
    private javax.swing.JLabel AVFighterLabel;
    private javax.swing.JLabel AVHPLabel;
    private javax.swing.JLabel AVHabilityLabel;
    private javax.swing.JLabel AVIDLabel;
    private javax.swing.JTextArea AVReinArea;
    private javax.swing.JLabel AVReinforcements;
    private javax.swing.JLabel AVpr1_1ID;
    private javax.swing.JLabel AVpr1_1image;
    private javax.swing.JLabel AVpr1_2ID;
    private javax.swing.JLabel AVpr1_2image;
    private javax.swing.JLabel AVpr1_3ID;
    private javax.swing.JLabel AVpr1_3image;
    private javax.swing.JLabel AVpr1_4ID;
    private javax.swing.JLabel AVpr1_4image;
    private javax.swing.JLabel AVpr2_1ID;
    private javax.swing.JLabel AVpr2_1image;
    private javax.swing.JLabel AVpr2_2ID;
    private javax.swing.JLabel AVpr2_2image;
    private javax.swing.JLabel AVpr2_3ID;
    private javax.swing.JLabel AVpr2_3image;
    private javax.swing.JLabel AVpr2_4ID;
    private javax.swing.JLabel AVpr2_4image;
    private javax.swing.JLabel AVpr3_1ID;
    private javax.swing.JLabel AVpr3_1image;
    private javax.swing.JLabel AVpr3_2ID;
    private javax.swing.JLabel AVpr3_2image;
    private javax.swing.JLabel AVpr3_3ID;
    private javax.swing.JLabel AVpr3_3image;
    private javax.swing.JLabel AVpr3_4ID;
    private javax.swing.JLabel AVpr3_4image;
    private javax.swing.JLabel RSAgilitylabel;
    private javax.swing.JLabel RSAtkLabel;
    private javax.swing.JLabel RSFighterLabel;
    private javax.swing.JLabel RSHPLabel;
    private javax.swing.JLabel RSHabilityLabel;
    private javax.swing.JLabel RSIDLabel;
    private javax.swing.JTextArea RSReinArea;
    private javax.swing.JLabel RSReinforcements;
    private javax.swing.JLabel RSpr1_1ID;
    private javax.swing.JLabel RSpr1_1image;
    private javax.swing.JLabel RSpr1_2ID;
    private javax.swing.JLabel RSpr1_2image;
    private javax.swing.JLabel RSpr1_3ID;
    private javax.swing.JLabel RSpr1_3image;
    private javax.swing.JLabel RSpr1_4ID;
    private javax.swing.JLabel RSpr1_4image;
    private javax.swing.JLabel RSpr2_1ID;
    private javax.swing.JLabel RSpr2_1image;
    private javax.swing.JLabel RSpr2_2ID;
    private javax.swing.JLabel RSpr2_2image;
    private javax.swing.JLabel RSpr2_3ID;
    private javax.swing.JLabel RSpr2_3image;
    private javax.swing.JLabel RSpr2_4ID;
    private javax.swing.JLabel RSpr2_4image;
    private javax.swing.JLabel RSpr3_1ID;
    private javax.swing.JLabel RSpr3_1image;
    private javax.swing.JLabel RSpr3_2ID;
    private javax.swing.JLabel RSpr3_2image;
    private javax.swing.JLabel RSpr3_3ID;
    private javax.swing.JLabel RSpr3_3image;
    private javax.swing.JLabel RSpr3_4ID;
    private javax.swing.JLabel RSpr3_4image;
    private javax.swing.JButton TimeButton;
    private javax.swing.JTextField TimeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel statusIA;
    // End of variables declaration//GEN-END:variables
}
